image: node:18

# include:
#   template: Verify/Load-Performance-Testing.gitlab-ci.yml


# Define the stages of your pipeline
stages:
  - build
  - test
  - package
  - deploy

variables:
  S3_BUCKET_NAME: "iconnect-builds"
  DEPLOYMENT_GROUP_NAME: "production-servers"
  APPLICATION_NAME: "iconnect"



# Job to build the Node.js application
build:
  stage: build
  script:
    - echo "Building the app..."
    - npm ci
  only:
    - branches
    - merge_requests

# # Job to run tests
unit-tests:
  stage: test
  script:
    - echo "Running tests"
    - npm ci
    - npm run test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    reports:
      junit: junit.xml
  only:
    - branches
    - merge_requests

upload_package:
  stage: package
  image: python:3
  script:
    - apt-get update -y && apt-get install -y zip awscli
    - zip -r app.zip .
    - aws s3 cp app.zip s3://$S3_BUCKET_NAME/


#Job to deploy the application to ec2 instance for merge request review
deploy:
  stage: deploy
  image: python:3
  when: manual
  script:
    - apt-get update -y && apt-get install -y awscli
    - aws deploy create-deployment \
        --application-name $APPLICATION_NAME \
        --deployment-group-name $DEPLOYMENT_GROUP_NAME \
        --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=app.zip
  only:
    - gitlab-codedeploy

