# Define the stages of your pipeline
stages:
  - build
  # - test
  # - deploy


# Job to build the Node.js application
build:
  stage: build
  image: node:18
  script:
    - npm ci
  cache:
    paths:
      - node_modules/
    key:
      files:
        - package-lock.json

# Job to run tests
test:
  stage: build
  image: node:18
  script:
    - npm run test

#job to package
package:
  stage: build
  image: node:18
  script:
    - npm install --only=prod
  artifacts:
    paths:
      - ./**/*

# Job to deploy the application
# deploy:
#   stage: deploy
#   image: node:14
#   script:
#     - npm run deploy
#   only:
#     - master
