image: node:18
# Define the stages of your pipeline
stages:
  - build
  - test
  # - deploy

cache:
  paths:
    - node_modules/
  key:
    files:
      - package-lock.json

# Job to build the Node.js application
build:
  stage: build
  script:
    - npm ci

# Job to run tests
test:
  stage: test
  script:
    - npm run test

#job to package
package:
  stage: build
  script:
    - npm install --omit=dev
  cache: []
  script:
    - mkdir myapp && cp -r * myapp/
  artifacts:
    paths:
      - myapp

# Job to deploy the application
# deploy:
#   stage: deploy
#   image: node:14
#   script:
#     - npm run deploy
#   only:
#     - master
