image: node:18

include:
  template: Verify/Load-Performance-Testing.gitlab-ci.yml

# Define the stages of your pipeline
stages:
  - test

#run load performace test in qa environemnt
load_performance:
  variables:
    K6_TEST_FILE: raw.githubusercontent.com/grafana/k6/master/examples/http_get.js



