image: node:18


# include:
#   - template: Jobs/Dependency-Scanning.gitlab-ci.yml
#   - template: Jobs/SAST.gitlab-ci.yml
#   - template: Security/Secret-Detection.gitlab-ci.yml

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  CONTAINER_BRANCH_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest 
  ECR_REPO_URL: "848889847135.dkr.ecr.ap-south-1.amazonaws.com/idevops"
  ECR_CONTAINER_NAME: $ECR_REPO_URL:$CI_COMMIT_REF_SLUG
  AWS_REGION: "ap-south-1"
  EKS_CLUSTER_NAME: "iDevOps"
  KUBECONFIG: "$HOME/.kube/config" 


# Define the stages of your pipeline
stages:
  # - build
  # - test
  - containerize
  - test

cache:
  paths:
    - node_modules/
  key:
    files:
      - package-lock.json

# Job to build the Node.js application
# build:
#   stage: build
#   script:
#     - echo "Building the app..."
#     - npm ci
#   only:
#     - branches
#     - merge_requests

# # Job to run tests
# unit-tests:
#   stage: test
#   script:
#     - echo "Running tests"
#     - npm run test
#   coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
#   artifacts:
#     reports:
#       junit: junit.xml
#   only:
#     - branches
#     - merge_requests

build-image:
  stage: containerize
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - echo "registry login"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - echo "build docker image"
    - docker build --pull -t $CONTAINER_BRANCH_IMAGE .
    - echo "push docker image"
    - docker push $CONTAINER_BRANCH_IMAGE
  only:
    - feature/docker-build-push

build-image-ecr:
  stage: containerize
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - echo "installing aws cli..."
    - apk --update add python3 pip3  # Install Python 3 for AWS CLI
    - pip3 install awscli
    - echo "Logging in to AWS ECR..."
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO_URL
    - echo "Logged in to AWS ECR"
  script:
    - echo "build docker image"
    - docker build --pull -t $ECR_CONTAINER_NAME .
    - echo "push docker image"
    - docker push $ECR_CONTAINER_NAME
  only:
    - feature/docker-build-push






