image: node:18

# Define the stages of your pipeline
stages:
  - build
  - package
  - deploy

variables:
  S3_BUCKET_NAME: "iconnect-builds"
  DEPLOYMENT_GROUP_NAME: "production-servers"
  APPLICATION_NAME: "iconnect"

# # Job to run tests
build-tests:
  stage: build
  script:
    - echo "Running tests"
    - npm ci
    - npm run test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    reports:
      junit: junit.xml
  only:
    - branches
    - merge_requests

upload_package:
  stage: package
  #image: python:3
  variables:
    NODE_ENV: production
  before_script:
    - apt-get update -y && apt-get install -y zip awscli
  script:
    - npm install
    - zip -r app-$CI_COMMIT_SHORT_SHA.zip .
    - aws s3 cp app-$CI_COMMIT_SHORT_SHA.zip s3://$S3_BUCKET_NAME/


#Job to deploy the application to ec2 instance for merge request review
deploy:
  stage: deploy
  image: python:3
  variables:
    GIT_STRATEGY: none
  script:
    - apt-get update -y && apt-get install -y awscli
    - >
       aws deploy create-deployment 
       --application-name $APPLICATION_NAME 
       --deployment-group-name $DEPLOYMENT_GROUP_NAME 
       --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=app-$CI_COMMIT_SHORT_SHA.zip
  only:
    - gitlab-codedeploy

