image: node:18
# Define the stages of your pipeline
stages:
  - build
  - test
  - package

cache:
  paths:
    - node_modules/
  key:
    files:
      - package-lock.json

# Job to build the Node.js application
build:
  stage: build
  script:
    - npm ci

# Job to run tests
test:
  stage: test
  script:
    - npm run test

#job to package
package:
  stage: package
  before_script:
    - apt-get update
    - apt-get install -y rsync
  script:
    - npm install --omit=dev
    - mkdir iconnect-app
    - rsync -av --exclude='iconnect-app' . iconnect-app/
  cache: []
  artifacts:
    paths:
      - iconnect-app

# Job to deploy the application
# deploy:
#   stage: deploy
#   image: node:14
#   script:
#     - npm run deploy
#   only:
#     - master
