image: node:18

include:
  template: Verify/Load-Performance-Testing.gitlab-ci.yml

# Define the stages of your pipeline
stages:
  - performance

postman-to-k6:
  stage: performance
  before_script:
    - npm install -g postman-to-k6
  script:
    - >
       curl -o collection.json 
       "https://api.getpostman.com/collections/28682864-cd88e482-b085-455b-bd2d-724fe3717829" 
       -H "X-Api-Key: $POSTMAN_API_KEY"
    
       curl -o environment.json 
       "https://api.getpostman.com/environments/28682864-4cd65385-2b2c-4e5d-9e46-d61309015511" 
       -H "X-Api-Key: $POSTMAN_API_KEY"
       
       ls

       echo "start ps to k6"

       postman-to-k6 collection.json --environment environment.json -o k6-script.js

       ls
  artifacts:
    paths:
      - k6-script.js
  
#run load performace test in qa environemnt
load_performance:
  stage: performance
  needs: ["postman-to-k6"]
  variables:
    K6_TEST_FILE: k6-script.js



