version: 0.0
os: linux
files:
  - source: /
    destination: /var/myapp
hooks:
  ApplicationStop:
    - location: Scripts/stop_server.sh
      timeout: 300
  BeforeInstall:
    - location: Scripts/install_dependencies.sh
      timeout: 300
  ApplicationStart:
    - location: Scripts/start_server.sh
      timeout: 300
  ValidateService:
    - location: Scripts/smoke_test.sh
      timeout: 300
